SELECT NAME 
FROM CLIENT 
WHERE CLIENT IN (
	SELECT CLIENT_ID
	FROM PROJECT 
	GROUP BY CLIENT_ID
	HAVING COUNT(ID) IN (
		SELECT COUNT(ID)
		FROM PROJECT 
		GROUP BY CLIENT_ID
		ORDER BY COUNT(ID) DESC
		LIMIT 1)
);